### ISSUE TITLE
what the “mil”, "mymil","mysparsemil","mysoftmil" stand for? Thanks!

### ISSUE THREAD

**Issue by guyucowboy** [wentaozhu/deep-mil-for-whole-mammogram-classification#10]
Hi, wentao zhu
      Great work! Thanks for sharing you codes!
      what the “mil”, "mymil","mysparsemil","mysoftmil" stand for?
      mil = Multiple Instance Learning
      How about others?
Best regards.
Thanks!
                              Gu Yu

**Comment by wentaozhu** [comment]
MIL is with max-pooling inference
mymil is with label assignment inference
mysparsemil is with sparisity inference
mysoftmil is todo inference, I think, it is sparity with label assignment. did not appear in the paper.

You can find the details in the MICCAI17 paper, Deep multi-instance networks with sparse label assignment for whole mammogram classification https://arxiv.org/pdf/1612.05968.pdf

After that, you can check the code carefully about it.

**Comment by guyucowboy** [comment]
Hi, wentao zhu
Thanks for your reply! 
I have an another question to ask you. Why do you use alexnet rather than vgg-16, vgg-19 in convnets-keras package?
Thanks.
Best regards.
Gu Yu

**Comment by wentaozhu** [comment]
Dear Gu,

You can definitely try the VGG-16 or VGG-19. At that, I did not have powerful machine and the dataset is not big.

Wentao

**Comment by guyucowboy** [comment]
Hi, wentao zhu. 
Thanks foy your reply!
Gu Yu
