### ISSUE TITLE
the original InBreast dataset

### ISSUE THREAD

**Issue by zhangrong1722** [wentaozhu/deep-mil-for-whole-mammogram-classification#12]
Do you have the original InBreast dataset available?I am interested in using the original INbreast Database in my neural network.

**Comment by wentaozhu** [comment]
You can get the orginal INBreast dataset from http://medicalresearch.inescporto.pt/breastresearch/index.php/Get_INbreast_Database

**Comment by zhangrong1722** [comment]
I have to send a request for the original dataset according to the link.I wonder whether I access the dataset from you.Thanks.

**Comment by wentaozhu** [comment]
Send me email please.

**Comment by zhangrong1722** [comment]
that's great.I have sent email to you.please have a check.
thank you very much.

**Comment by ghost** [comment]
@wentaozhu , @estelle1722  - I also need that dataset, is there any other way to get it (rather than sending a mail [here](http://medicalresearch.inescporto.pt/breastresearch/index.php/Get_INbreast_Database)?

**Comment by wentaozhu** [comment]
Send me an email

**Comment by brightstern** [comment]
@wentaozhu Hi I also need the dataset. Your help is highly appreciated.

**Comment by wentaozhu** [comment]
Send me an email.

**Comment by brightstern** [comment]
@wentaozhu . My email stem.mutondo@gmail.com.

**Comment by HuangQinJian** [comment]
> Send me an email.

Hi I also need the dataset. My email qjhuanglife@gmail.com.

**Comment by MarioAndresR** [comment]
Hi I also need the dataset. I'd be thankful with your help.
My e-mail: marandresrodriguezo@gmail.com

**Comment by cmarasinou** [comment]
Hi @wentaozhu,
 I also need the dataset. I'd be thankful with your help.
My e-mail: cmarasinou@gmail.com

**Comment by AkanshaKamboj** [comment]
Hi @wentaozhu,
Can i get the dataset? I need it for my project. 
My email id: akansha.1297@gmail.com

**Comment by yoheimatt** [comment]
Dear @wentaozhu , 
Can I have access to the dataset? My email is pennxpl@gmail.com
Thanks in advance!

**Comment by dhruvek** [comment]
Dear @wentaozhu,

Request to kindly provide access to the dataset. My email is dhruvedeepakk@gmail.com.

**Comment by yufei1900** [comment]
Dear @wentaozhu ,
Can I get the dataset? My email is yfei1900@gmail.com
Thanks very much!

**Comment by wentaozhu** [comment]
If you cannot find INbreast dataset from the official site, you may download it from here.
https://drive.google.com/file/d/19n-p9p9C0eCQA1ybm6wkMo-bbeccT_62/view?usp=sharing

Please add our work to your references. Thank you!

Deep multi-instance networks with sparse label assignment for whole mammogram classification, MICCAI 2017.

Adversarial deep structured nets for mass segmentation from mammograms, ISBI 2018

**Comment by Kevin-xhj** [comment]
Can I get the dataset, I need it for my project. I'd be thankful with your help.
My email id: joseph.xhj@gmail.com

**Comment by waheedshahzad** [comment]
Can you please send me INbreast dataset? I need it for my project. I'd be thankful with your help.
My email id: waheedshahzad6@gmail.com

**Comment by gnanavardhani** [comment]
Dear  @wentaozhu ,
Can you please send me INbreast data set. It would be helpful for my project. 
Thank you
Mail id: vardhanikanamarlapudi@gmail.com

**Comment by Khalifa1997** [comment]
I would love to have this dataset for my project aswell,
my email :khalifaahmedd321@gmail.com

**Comment by MarwaMamdouh** [comment]
Dear @wentaozhu ,
Can you please send me INbreast data set. It would be helpful for my project.
Thank you
My Mail : marwa.khalef@mu.edu.eg

**Comment by MarwaMamdouh** [comment]
> Dear @gnanavardhani ,
> Can you please send me INbreast data set. It would be helpful for my project.
> Thank you
> Mail id: marwa.khalef@mu.edu.eg

**Comment by sanmathi-g** [comment]
Can you please send me INbreast data set. It would be helpful for my project.
Thank you
mail id: sanmathigrao24@gmail.com

**Comment by korcsogdenes** [comment]
Dear @wentaozhu  ,
Can you please send me the INbreast data set. It would be very helpful for my project.
Thank you
Mail id: deneskorcsog@gmail.com

**Comment by sanmathi-g** [comment]
I have sent through another email, check it

**Comment by korcsogdenes** [comment]
Thank you @sanmathi-g !
I have one more question.

Are these all malignant cases?
Or if not, how can i determine if it's benign or malignant?

**Comment by wentaozhu** [comment]
> Thank you @sanmathi-g !
> I have one more question.
> 
> Are these all malignant cases?
> Or if not, how can i determine if it's benign or malignant?

You can get the BI-RADS from the annotation. If it is {4, 5, 6}, the case is positive. Otherwise, it is negative.

**Comment by Mouna-br** [comment]
Hallo Wentaozhu, 
can you please send me the INbreast dataset (email: ulemr@student.kit.edu). I need it for my thesis... 
thanks a lot :)

**Comment by mp-lu** [comment]
Hello @wentaozhu 
Can you send the original INbreast dataset to me?
Mail id: bee@g-mail.nsysu.edu.tw
Thx

**Comment by DinuwanB** [comment]
> 
> 
> that's great.I have sent email to you.please have a check.
> thank you very much.

Do you have a data set?

**Comment by DinuwanB** [comment]
Hello @wentaozhu 

I need this data set for my final year research. If you can send me data set It's big help for me.
my Email - dinubhagya97@gmail.com
Thank You !

**Comment by kaypositive** [comment]
Hello,
Please I also need the dataset. kayode_olaniyi@yahoo.com

**Comment by kaypositive** [comment]
Hello @wentaozhu 
Please I also need this dataset. My email : olaniyikayodeade@gmail.com

**Comment by sshamekhi** [comment]
Hi, @wentaozhu
lease I also need this dataset. My email : shamekhi@sut.ac.ir

**Comment by ypy516478793** [comment]
Hi, @wentaozhu 
The original INBreast dataset is broken. Could you share the dataset with me? My email is ypy516478793@gmail.com.
Thanks

**Comment by kaypositive** [comment]
Mine too. I could not access anything.

Kayode A. Olaniyi
MCPN, MBCS, MNCS, IAENG, MCP, CCNA.Electrical & Computer Engineering+27 747153822 +234 8033770869
 

    On Friday, March 5, 2021, 6:14:19 PM GMT+2, ypy516478793 <notifications@github.com> wrote:  
 
 


Hi, @wentaozhu
The original INBreast dataset is broken. Could you share the dataset with me? My email is ypy516478793@gmail.com.
Thanks

**Comment by ManuLasker** [comment]
Hi, @wentaozhu.
Please I also need this dataset. My email: pemanuel@uninorte.edu.co

**Comment by devikasivan** [comment]
Hi, @wentaozhu.
Please I also need this dataset. My email: devs.sivan@gmail.com

**Comment by Anjaliiitr** [comment]
Please send me the dataset on anjaligautam@iiita.ac.in

**Comment by cameliaburlacu98** [comment]
Hi, @wentaozhu
The original INBreast dataset is broken. Could you share the dataset with me? My email : camelia.adelina98@gmail.com
Thanks

**Comment by pijiande** [comment]
Hi, @wentaozhu
Could you share the dataset with me? My email : pijd19@lzu.edu.cn
Thanks

**Comment by Farooqmuhammadumar** [comment]
Hi, @wentaozhu
Please send me original dataset with mass on my email My email : umarfarooq@a.ut.ac.kr
Thanks

**Comment by tdh512194** [comment]
Hi, @wentaozhu 
I cannot access the original INBreast dataset, could you share to my email: tdh512194@gmail.com
Thanks!!

**Comment by vishal007-0** [comment]
Hi, @wentaozhu
I cannot access the original INBreast dataset, could you share to my email: postvishal14@gmail.com
Thanks!!

**Comment by XuZikang** [comment]
Hi, @wentaozhu
I cannot access the original INBreast dataset, could you share to my email: 942674879@qq.com
Thanks!!

**Comment by Tasfia266** [comment]
Please share the dataset with me. Its a request please. My email: ornitasfia3@gmail.com

**Comment by DiegoStaub** [comment]
The original INBreast dataset is broken. Could you share the dataset with me? My email : diegostaubfelipe@gmail.com
Thanks

**Comment by ozkilim** [comment]
The original INBreast dataset is broken. Could you share the dataset with me? My email : ozkilim@hotmail.co.uk
Thanks

**Comment by sarodepranav** [comment]
Hello, can you please share the INBreast dataset with me? My Email - sarodepranav@gmail.com

**Comment by lulu-kd** [comment]
Hey, can someone pleaseeee send me the INBreast dataset. My Email: Lasyan99@hotmail.de My Deadline is on Thursday 🥺😩😭😭

**Comment by InesDomingues** [comment]
Requests for InBreast dataset should be directed at inesdomingues@gmail.com.

**Comment by programmer5889** [comment]
> You can get the original INBreast dataset from http://medicalresearch.inescporto.pt/breastresearch/index.php/Get_INbreast_Database

Sir this page is not found, I want the original **Inbreast Dataset**  which contains **extras folder**  that has ground-truth results for mass segmentation.

**Comment by programmer5889** [comment]
> Requests for InBreast dataset should be directed at [inesdomingues@gmail.com](mailto:inesdomingues@gmail.com).

I sent you email please check email

**Comment by programmer5889** [comment]
Hi,
I downloaded Inbreast Dataset  but it does not fount extra folders,

_INbreast/extras/MassSegmentationMasks/
INbreast/extras/CalcificationSegmentationMasks/_


Please provide me original dataset.

**Comment by Pooryamn** [comment]
Can I get the dataset, I need it for my project. I'd be thankful with your help. 
my email: Poorya.m.n.b@gmail.com

**Comment by ritvikgit** [comment]
Hello, I am doing the project on breast cancer diagnosis. Can you please help me get this data set. my email: email2ritvik2@gmail.com

**Comment by lsbmsb** [comment]
I also need a dataset, this is my email sunybuffalo21@gmail.com.
Thanks in advance!

**Comment by gonzaiq** [comment]
Hello,

I cannot find in the annotations file if each image is labeled as cancer or not. I know that one could take the BIRADS score and then infer if the image  is benign or malignant, but this is not recommendable as usually a biopsy is needed to confirm this (specially for BIRADS scores 3 and 4). In the InBreast paper (https://core.ac.uk/download/pdf/47139244.pdf), the authors say that biopsies were performed for the BIRADS cases 3, 4 and 5. However, in the annotations, the result of the biopsy (benign, malignant) is not clear. 

Do you have the original cancer/no cancer labels for each image ?

Thanks in advance,

Best.

Gonzalo

**Comment by sunrain0230** [comment]
Can I get the dataset, I need it for my project. I'd be thankful with your help.
my email: sunrain0230@gmail.com

**Comment by mahmadi92** [comment]
Hi, @wentaozhu
Could you share the dataset with me? I need it for my project. I'd be thankful with your help. My email is m.ahmadi92@gmail.com.
Thanks

**Comment by Jungjaewon** [comment]
Hello, @wentaozhu 
Could you send me the dataset? My email is woodcook48@gmail.com
Thanks for your sharing.

**Comment by calledammar** [comment]
Hello, @wentaozhu
Could you send me the dataset? My email is  ammaralruhaimii@gmail.com
I need it for my graduation project
Thanks for your sharing.

**Comment by mabt1377** [comment]
i also need that  dataset , I need it for my project. I'd be thankful with your help.
my email : bahmanimabt1377tbam@gmail.com

**Comment by malekzaki** [comment]
could you please send me the dataset? my email is malek.zaki2310@gmail.com, i need it for my grad project, thanks in advance!

**Comment by ChengFeng111** [comment]
Hello, @wentaozhu
Could you send me the dataset? My email is cf@stu.tyust.edu.cn


Thanks for your sharing.

**Comment by Tiagoblima** [comment]
I also need the dataset could you share with my e-mail: tbl3@cin.ufpe.br

**Comment by MatijaBazec** [comment]
Hi, @wentaozhu
Could you share the dataset with me asl well? My email : matijajecar123@gmail.com
Thanks!

**Comment by Marwen-Nahdi-0** [comment]
Could you share the dataset with me asl well?  [nahdimarwen0@gmail.com](mailto:nahdimarwen0@gmail.com).
Thanks!

**Comment by S3TE** [comment]
The dataset cannot be opened can you plz send me the link or share the link? for my project

**Comment by S3TE** [comment]
> The dataset cannot be opened can you plz send me the link or share the link? for my project

My Mail ID is s3pythonprogramm@gmail.com

**Comment by Suaiba** [comment]
Hi @wentaozhu, could you please share the data with me as well? I need it for my research project. My email is ssa195@uit.no. Thanks!

**Comment by Bh24** [comment]
Hi @wentaozhu , please can you send me the original dataset, I need it for my research project. My email is bhavnasetty@gmail.com. Thank you so much for your help!!

**Comment by raidenwang** [comment]
Dear @wentaozhu ,
Can I have access to the dataset? I need it for my research project. My email is  raiden_wang520@163.com
Thanks in advance!

**Comment by vinaykmr116** [comment]
Hi, @wentaozhu

Could you share the dataset with me? I need it for my project. I'd be thankful with your help. My email is vinaykmrphd@gmail.com

Thanks

**Comment by InesDomingues** [comment]
To whom it may concern,

Please find enclosed the Transfer Agreement.
We kindly ask you to complete where appropriate, print it, sign, and email
us back a scanned copy.
After receiving the signed transfer agreement, I will email you the
instructions to download the INbreast database.

Sincerely,
Inês Campos Monteiro Sabino Domingues
Research Center of the Portuguese Institute of Oncology of Porto (CI-IPOP),
Medical Physics, Radiobiology and Radiological Protection Group,
Rua Dr. António Bernardino de Almeida 4200-072 Porto
