### ISSUE TITLE
在Inbreast数据库中，当图像中有多个肿块时，肿块分类和图像分类都一样吗？

### ISSUE THREAD

**Issue by lixiangamy** [wentaozhu/deep-mil-for-whole-mammogram-classification#14]
在Inbreast数据库中，当图像中有多个肿块时，肿块分类和图像分类都一样吗？您的肿块分类结果精度是如何计算的呢？

**Comment by wentaozhu** [comment]
If there are many masses in one mammogram, the classification result for the mammogram may be different from the result for each mass. If there is one malignant mass in the mammogram, the mammogram is malignant. If there is no mammogram mass in the mammogram, the mammogram is benign. It is exactly the multi-instance learning problem. We proposed the deep multi-instance learning to get the mammogram classification result and calculate the mammogram-level accuracy.
