### ISSUE TITLE
extractdreamdata() is not defined

### ISSUE THREAD

**Issue by Nicholasli1995** [wentaozhu/deep-mil-for-whole-mammogram-classification#16]
It seems the related code for usedream and data augmentation is not included. The following function ends up in error.
def loaddata(fold, totalfold, usedream=True, aug=True):

**Comment by wentaozhu** [comment]
Because i do not have the dream data. If you have the additional data, you may set it as true and debug yourself. Good luck!

**Comment by lixinHUST** [comment]
Excuse me, what is the dream data?

> Because i do not have the dream data. If you have the additional data, you may set it as true and debug yourself. Good luck!
