### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by yishanyang** [wentaozhu/deep-mil-for-whole-mammogram-classification#4]
Hi, wentao
Here is an error when I run the inbreast.py :

   Traceback (most recent call last):
     File "inbreast.py", line 292, in <module>
       traindata, trainlabel, testdata, testlabel = loaddata(0, 5)
     File "inbreast.py", line 200, in loaddata
       ims = loadim(mydictkey[trainindex[i]]+'.pickle', aug=aug)
   TypeError: loadim() got an unexpected keyword argument 'aug'

It will be grateful if you can help me to solve the problem.

Danyang Li

**Comment by wentaozhu** [comment]
Hi Danyang,

You can try to comment the aug parameter.

Thanks,
Wentao

**Comment by yishanyang** [comment]
Hi wentao

I have solved it. Thanks very much!

Danyang Li
