### ISSUE TITLE
How to do the  visualization of predicted malignant probabilities?

### ISSUE THREAD

**Issue by c1a1o1** [wentaozhu/deep-mil-for-whole-mammogram-classification#8]
How to do the  visualization of predicted malignant probabilities?

**Comment by wentaozhu** [comment]
https://github.com/fchollet/keras/issues/41

**Comment by c1a1o1** [comment]
Thanks very much!

**Comment by c1a1o1** [comment]
It  can make the result like Fig. 4 in your great  paper???

**Comment by wentaozhu** [comment]
Sure. You can visualize the channel 1 or 1- channel 0 for malignant probability.
