### ISSUE TITLE
which is the backend for keras, theano or tensorflow?

### ISSUE THREAD

**Issue by lxmwust** [wentaozhu/deep-mil-for-whole-mammogram-classification#9]
att, it seems to be using theano. I tried to use tensorflow, it report a dimension error for Alexnet network. I would be better to declare it clearly in the document.
Besides, the modified convnetskeras (outdated) also reported several errors. The code is not easy to setup.

**Comment by wentaozhu** [comment]
Yes. It is theano backend. I think now keras has added many features and there is no one to support theano any more. I am very sorry for the outdated. It is very hard to maintenance a project for a long time. But I think it is easy for you to update it based on the existing code because there are some api function interfaces changed.

**Comment by lxmwust** [comment]
Thank you for the reply. While I still think the update is not so easy. In fact, I tried to adapt the code. One problem I encountered is that it depends "convnets-keras" (which is theano based, and not supported anymore). I tried to modify convnets-keras to use tensorflow, after went through "issues" regard it and made some small changes, while I can run convnets-keras now, but the result I obtained is much worse than the result show on 'convnets-keras'. Thus I guess I will not be able run your code, since I am not familar to theano, and can not solve the 'convnets-keras' depence problem.

**Comment by Estarcontigo** [comment]
@lxmwust 
Hello, I want to know if you solved this problem? What is the solution? Is the code running?
Looking forward to your reply.

**Comment by LLYXC** [comment]
Modify your Keras config ~/.keras/keras.json, set backend tensorflow, image_data_format to channel_first will do. Still some other changes in the custom_layers should be made in order to run the code.

**Comment by Estarcontigo** [comment]
Thank you for your response, I already fix it.

________________________________
